sudo: false
language: node_js
node_js:
- 6.9.1
script: npm run ci
branches:
  only:
  - master
cache: yarn
env:
  global:
    secure: AZyLrM+LB79HMmAdJbv63tT9vBe7UguVfe8aAXR6JgL+yi04eKoPyAjP4qrVSHNt59ZlU551eTMCeG4A5TUEGJq/OpXbaq211Myazq4+LTe0C9cKD8ePg2MgqWPoYo/gSf8m8J+uI2iGfGK+LWJryTuRw7OBLarZJ/IdKnDklLd+qTxcvKEhRn+aQP/UqYl3n5UV6C1v8wmkFY43UskGooQyyU/XaXi++2AhaW/T8nzQmKPkPmlyqsJeIzA/g/UM/kbiQgokugrWYqprCvWzvD9seI0M5YzqVatwf9wbb8/SJ3BO6HjQqJR3eUb4ERFhMygaIaLnFqbf8iy+RAKd/4k4bG+4w80R6SDTSL36+2EpGMVzYiAw7ReZUCIdCWLEx3L/zKGzS5p1q+dncV9EnJ7x0mgatlEsDH9fJ4Yteoz9cpDDDR8aAEnZPc5C1+Hup5gnFf7WecoDApItQ5SGGr2kH2QIVeZbFxvYXVo8NWk7CxqvETUA0WjoEc4Zjx4CkHz9uO+AHm82BU7Pmm9HhKKShvfLyvhT7P5HmkDsFuo6sfXaewQU+w3nhwrthHeUVWU6EkFsD2MCHogqgSv1xi41sYA/6bu8v6y9Svd0gFEtKQQ66A0xYJPcIYTyVOcKOyNORKlpLRqErrCmpMRPeoPPAmuDD5GtWatUCDvbIjg=
