version: '2'

volumes:  
  node_modules:
  express_node_modules:
  forage_node_modules:
  graphql_node_modules:
  child_node_modules:
  fs_node_modules:
  inquirer_node_modules:
  http_node_modules:
  logger_node_modules:
  mongoose_node_modules:
  task_node_modules:
  hmr_node_modules:

services:
  mongo:
    image: mongo:3.4.0
    command: mongod --quiet --storageEngine mmapv1  

  node:
    #image: cycler-dev-node
    build: . 
    working_dir: /cycler
    volumes:      
      - .:/cycler
      - node_modules:/cycler/node_modules
      - express_node_modules:/cycler/express/node_modules
      - forage_node_modules:/cycler/forage/node_modules
      - graphql_node_modules:/cycler/graphql/node_modules
      - child_node_modules:/cycler/child/node_modules
      - inquirer_node_modules:/cycler/inquirer/node_modules
      - fs_node_modules:/cycler/fs/node_modules
      - http_node_modules:/cycler/http/node_modules
      - logger_node_modules:/cycler/logger/node_modules
      - mongoose_node_modules:/cycler/mongoose/node_modules
      - task_node_modules:/cycler/task/node_modules
      - hmr_node_modules:/cycler/hmr/node_modules
    entrypoint: sh .scripts/watch-deps.sh
    depends_on:
      - mongo
    
    